# Generated by Django 3.1.11 on 2021-05-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_curator',
            new_name='is_staff',
        ),
    ]
